package com.erumf.cards.locations;

import org.jgrapht.Graph;
import org.jgrapht.graph.SimpleGraph;

import com.erumf.cards.locations.Locations.AmonHen;
import com.erumf.cards.locations.Locations.BagEnd;
import com.erumf.cards.locations.Locations.BanditLair;
import com.erumf.cards.locations.Locations.BaradDur;
import com.erumf.cards.locations.Locations.BarrowDowns;
import com.erumf.cards.locations.Locations.BeornsHouse;
import com.erumf.cards.locations.Locations.BlueMountainDwarfHold;
import com.erumf.cards.locations.Locations.Bree;
import com.erumf.cards.locations.Locations.CamethBrin;
import com.erumf.cards.locations.Locations.CarnDum;
import com.erumf.cards.locations.Locations.CavesOfUlund;
import com.erumf.cards.locations.Locations.CirithUngol;
import com.erumf.cards.locations.Locations.DancingSpire;
import com.erumf.cards.locations.Locations.DeadMarshes;
import com.erumf.cards.locations.Locations.DimrillDale;
import com.erumf.cards.locations.Locations.DolAmroth;
import com.erumf.cards.locations.Locations.DolGuldur;
import com.erumf.cards.locations.Locations.DruadanForest;
import com.erumf.cards.locations.Locations.Dunharrow;
import com.erumf.cards.locations.Locations.DunnishClanHold;
import com.erumf.cards.locations.Locations.EaglesEyrie;
import com.erumf.cards.locations.Locations.EasterlingCamp;
import com.erumf.cards.locations.Locations.Edhellond;
import com.erumf.cards.locations.Locations.Edoras;
import com.erumf.cards.locations.Locations.Ettenmoors;
import com.erumf.cards.locations.Locations.GladdenFields;
import com.erumf.cards.locations.Locations.GlitteringCaves;
import com.erumf.cards.locations.Locations.GoblinGate;
import com.erumf.cards.locations.Locations.GreyHavens;
import com.erumf.cards.locations.Locations.HennethAnnun;
import com.erumf.cards.locations.Locations.Himring;
import com.erumf.cards.locations.Locations.Irerock;
import com.erumf.cards.locations.Locations.IronHillDwarfHold;
import com.erumf.cards.locations.Locations.Isengard;
import com.erumf.cards.locations.Locations.IslesOfTheDeadThatLive;
import com.erumf.cards.locations.Locations.LakeTown;
import com.erumf.cards.locations.Locations.LondGalen;
import com.erumf.cards.locations.Locations.Lorien;
import com.erumf.cards.locations.Locations.LossadanCairn;
import com.erumf.cards.locations.Locations.LossadanCamp;
import com.erumf.cards.locations.Locations.MinasMorgul;
import com.erumf.cards.locations.Locations.MinasTirith;
import com.erumf.cards.locations.Locations.Moria;
import com.erumf.cards.locations.Locations.MountDoom;
import com.erumf.cards.locations.Locations.MountGram;
import com.erumf.cards.locations.Locations.MountGundabad;
import com.erumf.cards.locations.Locations.OldForest;
import com.erumf.cards.locations.Locations.OstInEdhil;
import com.erumf.cards.locations.Locations.Pelargir;
import com.erumf.cards.locations.Locations.Rhosgobel;
import com.erumf.cards.locations.Locations.Rivendell;
import com.erumf.cards.locations.Locations.RuinedSignalTower;
import com.erumf.cards.locations.Locations.SarnGoriwing;
import com.erumf.cards.locations.Locations.ShelobsLair;
import com.erumf.cards.locations.Locations.ShrelKain;
import com.erumf.cards.locations.Locations.SouthronOasis;
import com.erumf.cards.locations.Locations.StoneCircle;
import com.erumf.cards.locations.Locations.TheLonelyMountain;
import com.erumf.cards.locations.Locations.TheStones;
import com.erumf.cards.locations.Locations.TheWhiteTowers;
import com.erumf.cards.locations.Locations.TheWindThrone;
import com.erumf.cards.locations.Locations.ThranduilsHalls;
import com.erumf.cards.locations.Locations.Tolfalas;
import com.erumf.cards.locations.Locations.ValeOfErech;
import com.erumf.cards.locations.Locations.VariagCamp;
import com.erumf.cards.locations.Locations.Weathertop;
import com.erumf.cards.locations.Locations.Wellinghall;
import com.erumf.cards.locations.Locations.WoodmenTown;
import com.erumf.cards.locations.Locations.WosePassageHold;
import com.erumf.elements.Haven;
import com.erumf.elements.Location;
import com.erumf.utils.graph.DefaultPathEdge;

public class Locations2 {

    public static Graph<Location, DefaultPathEdge> generateDefaultLocations() {
        Graph<Location, DefaultPathEdge> pathsGraph = new SimpleGraph<>(DefaultPathEdge.class);
        
        Haven rivendell = new Rivendell();
        Haven lorien = new Lorien();
        Haven greyHavens = new GreyHavens();
        Haven edhellond = new Edhellond();

        Location barrowDowns = new BarrowDowns();
        Location dunnishClanHold = new DunnishClanHold();
        Location bree = new Bree();
        Location goblinGate = new GoblinGate();
        Location isengard = new Isengard();
        Location wellinghall = new Wellinghall();
        Location edoras = new Edoras();
        Location minasTirith = new MinasTirith();
        Location deadMarshes = new DeadMarshes();
        Location thranduilsHalls = new ThranduilsHalls();
        Location mountGundabad = new MountGundabad();
        Location moria = new Moria();
        Location dimrillDale = new DimrillDale();
        Location dolAmroth = new DolAmroth();
        Location dancingSpire = new DancingSpire();
        Location cavesOfUlund = new CavesOfUlund();
        Location cirithUngol = new CirithUngol();
        Location carnDum = new CarnDum();
        Location dolGuldur = new DolGuldur();
        Location baradDur = new BaradDur();
        Location bagEnd = new BagEnd();
        Location beornsHouse = new BeornsHouse();
        Location blueMountainDwarfHold = new BlueMountainDwarfHold();
        Location easterlingCamp = new EasterlingCamp();
        Location ettenmoors = new Ettenmoors();
        Location glitteringCaves = new GlitteringCaves();
        Location gladdenFields = new GladdenFields();
        Location camethBrin = new CamethBrin();
        Location amonHen = new AmonHen();
        Location banditLair = new BanditLair();
        Location dunharrow = new Dunharrow();
        Location druadanForest = new DruadanForest();
        Location eaglesEyrie = new EaglesEyrie();
        Location lossadanCairn = new LossadanCairn();
        Location lakeTown = new LakeTown();
        Location londGalen = new LondGalen();
        Location islesOfTheDeadThatLive = new IslesOfTheDeadThatLive();
        Location irerock = new Irerock();
        Location ironHillDwarfHold = new IronHillDwarfHold();
        Location hennethAnnun = new HennethAnnun();
        Location himring = new Himring();
        Location theLonelyMountain = new TheLonelyMountain();
        Location theStones = new TheStones();
        Location southronOasis = new SouthronOasis();
        Location stoneCircle = new StoneCircle();
        Location shelobsLair = new ShelobsLair();
        Location shrelKain = new ShrelKain();
        Location ruinedSignalTower = new RuinedSignalTower();
        Location sarnGoriwing = new SarnGoriwing();
        Location rhosgobel = new Rhosgobel();
        Location pelargir = new Pelargir();
        Location oldForest = new OldForest();
        Location ostInEdhil = new OstInEdhil();
        Location mountGram = new MountGram();
        Location mountDoom = new MountDoom();
        Location minasMorgul = new MinasMorgul();
        Location lossadanCamp = new LossadanCamp();
        Location wosePassageHold = new WosePassageHold();
        Location theWhiteTowers = new TheWhiteTowers();
        Location woodmenTown = new WoodmenTown();
        Location variagCamp = new VariagCamp();
        Location weathertop = new Weathertop();
        Location tolfalas = new Tolfalas();
        Location valeOfErech = new ValeOfErech();
        Location theWindThrone = new TheWindThrone();

        pathsGraph.addVertex(rivendell);
        pathsGraph.addVertex(lorien);
        pathsGraph.addVertex(greyHavens);
        pathsGraph.addVertex(edhellond);
        pathsGraph.addVertex(barrowDowns);
        pathsGraph.addVertex(dunnishClanHold);
        pathsGraph.addVertex(bree);
        pathsGraph.addVertex(goblinGate);
        pathsGraph.addVertex(isengard);
        pathsGraph.addVertex(wellinghall);
        pathsGraph.addVertex(edoras);
        pathsGraph.addVertex(minasTirith);
        pathsGraph.addVertex(deadMarshes);
        pathsGraph.addVertex(thranduilsHalls);
        pathsGraph.addVertex(mountGundabad);
        pathsGraph.addVertex(moria);
        pathsGraph.addVertex(dimrillDale);
        pathsGraph.addVertex(dolAmroth);
        pathsGraph.addVertex(dancingSpire);
        pathsGraph.addVertex(cavesOfUlund);
        pathsGraph.addVertex(cirithUngol);
        pathsGraph.addVertex(carnDum);
        pathsGraph.addVertex(dolGuldur);
        pathsGraph.addVertex(baradDur);
        pathsGraph.addVertex(bagEnd);
        pathsGraph.addVertex(beornsHouse);
        pathsGraph.addVertex(blueMountainDwarfHold);
        pathsGraph.addVertex(easterlingCamp);
        pathsGraph.addVertex(ettenmoors);
        pathsGraph.addVertex(glitteringCaves);
        pathsGraph.addVertex(gladdenFields);
        pathsGraph.addVertex(camethBrin);
        pathsGraph.addVertex(amonHen);
        pathsGraph.addVertex(banditLair);
        pathsGraph.addVertex(dunharrow);
        pathsGraph.addVertex(druadanForest);
        pathsGraph.addVertex(eaglesEyrie);
        pathsGraph.addVertex(lossadanCairn);
        pathsGraph.addVertex(lakeTown);
        pathsGraph.addVertex(londGalen);
        pathsGraph.addVertex(islesOfTheDeadThatLive);
        pathsGraph.addVertex(irerock);
        pathsGraph.addVertex(ironHillDwarfHold);
        pathsGraph.addVertex(hennethAnnun);
        pathsGraph.addVertex(himring);
        pathsGraph.addVertex(theLonelyMountain);
        pathsGraph.addVertex(theStones);
        pathsGraph.addVertex(southronOasis);
        pathsGraph.addVertex(stoneCircle);
        pathsGraph.addVertex(shelobsLair);
        pathsGraph.addVertex(shrelKain);
        pathsGraph.addVertex(ruinedSignalTower);
        pathsGraph.addVertex(sarnGoriwing);
        pathsGraph.addVertex(rhosgobel);
        pathsGraph.addVertex(pelargir);
        pathsGraph.addVertex(oldForest);
        pathsGraph.addVertex(ostInEdhil);
        pathsGraph.addVertex(mountGram);
        pathsGraph.addVertex(mountDoom);
        pathsGraph.addVertex(minasMorgul);
        pathsGraph.addVertex(lossadanCamp);
        pathsGraph.addVertex(wosePassageHold);
        pathsGraph.addVertex(theWhiteTowers);
        pathsGraph.addVertex(woodmenTown);
        pathsGraph.addVertex(variagCamp);
        pathsGraph.addVertex(weathertop);
        pathsGraph.addVertex(tolfalas);
        pathsGraph.addVertex(valeOfErech);
        pathsGraph.addVertex(theWindThrone);

        //Havens routes
        pathsGraph.addEdge(rivendell, lorien, new DefaultPathEdge(lorien.getRoute()));
        pathsGraph.addEdge(lorien, edhellond, new DefaultPathEdge(edhellond.getRoute2()));
        pathsGraph.addEdge(edhellond, greyHavens, new DefaultPathEdge(greyHavens.getRoute2()));
        pathsGraph.addEdge(greyHavens, rivendell, new DefaultPathEdge(rivendell.getRoute2()));


        //Other routes
        pathsGraph.addEdge(rivendell, barrowDowns, new DefaultPathEdge(barrowDowns.getRoute()));
        pathsGraph.addEdge(rivendell, dunnishClanHold, new DefaultPathEdge(dunnishClanHold.getRoute()));
        pathsGraph.addEdge(rivendell, bree, new DefaultPathEdge(bree.getRoute()));
        pathsGraph.addEdge(rivendell, goblinGate, new DefaultPathEdge(goblinGate.getRoute()));
        pathsGraph.addEdge(lorien, isengard, new DefaultPathEdge(isengard.getRoute()));
        pathsGraph.addEdge(lorien, wellinghall, new DefaultPathEdge(wellinghall.getRoute()));
        pathsGraph.addEdge(lorien, edoras, new DefaultPathEdge(edoras.getRoute()));
        pathsGraph.addEdge(lorien, minasTirith, new DefaultPathEdge(minasTirith.getRoute()));
        pathsGraph.addEdge(lorien, deadMarshes, new DefaultPathEdge(deadMarshes.getRoute()));
        pathsGraph.addEdge(lorien, thranduilsHalls, new DefaultPathEdge(thranduilsHalls.getRoute()));
        pathsGraph.addEdge(lorien, mountGundabad, new DefaultPathEdge(mountGundabad.getRoute()));
        pathsGraph.addEdge(lorien, moria, new DefaultPathEdge(moria.getRoute()));
        pathsGraph.addEdge(lorien, dimrillDale, new DefaultPathEdge(dimrillDale.getRoute()));
        pathsGraph.addEdge(edhellond, dolAmroth, new DefaultPathEdge(dolAmroth.getRoute()));
        pathsGraph.addEdge(lorien, dancingSpire, new DefaultPathEdge(dancingSpire.getRoute()));
        pathsGraph.addEdge(lorien, cavesOfUlund, new DefaultPathEdge(cavesOfUlund.getRoute()));
        pathsGraph.addEdge(lorien, cirithUngol, new DefaultPathEdge(cirithUngol.getRoute()));
        pathsGraph.addEdge(rivendell, carnDum, new DefaultPathEdge(carnDum.getRoute()));
        pathsGraph.addEdge(lorien, dolGuldur, new DefaultPathEdge(dolGuldur.getRoute()));
        pathsGraph.addEdge(lorien, baradDur, new DefaultPathEdge(baradDur.getRoute()));
        pathsGraph.addEdge(rivendell, bagEnd, new DefaultPathEdge(bagEnd.getRoute()));
        pathsGraph.addEdge(lorien, beornsHouse, new DefaultPathEdge(beornsHouse.getRoute()));
        pathsGraph.addEdge(greyHavens, blueMountainDwarfHold, new DefaultPathEdge(blueMountainDwarfHold.getRoute()));
        pathsGraph.addEdge(lorien, easterlingCamp, new DefaultPathEdge(easterlingCamp.getRoute()));
        pathsGraph.addEdge(rivendell, ettenmoors, new DefaultPathEdge(ettenmoors.getRoute()));
        pathsGraph.addEdge(lorien, glitteringCaves, new DefaultPathEdge(glitteringCaves.getRoute()));
        pathsGraph.addEdge(lorien, gladdenFields, new DefaultPathEdge(gladdenFields.getRoute()));
        pathsGraph.addEdge(rivendell, camethBrin, new DefaultPathEdge(camethBrin.getRoute()));
        pathsGraph.addEdge(lorien, amonHen, new DefaultPathEdge(amonHen.getRoute()));
        pathsGraph.addEdge(lorien, banditLair, new DefaultPathEdge(banditLair.getRoute()));
        pathsGraph.addEdge(lorien, dunharrow, new DefaultPathEdge(dunharrow.getRoute()));
        pathsGraph.addEdge(lorien, druadanForest, new DefaultPathEdge(druadanForest.getRoute()));
        pathsGraph.addEdge(lorien, eaglesEyrie, new DefaultPathEdge(eaglesEyrie.getRoute()));
        pathsGraph.addEdge(rivendell, lossadanCairn, new DefaultPathEdge(lossadanCairn.getRoute()));
        pathsGraph.addEdge(lorien, lakeTown, new DefaultPathEdge(lakeTown.getRoute()));
        pathsGraph.addEdge(edhellond, londGalen, new DefaultPathEdge(londGalen.getRoute()));
        pathsGraph.addEdge(greyHavens, islesOfTheDeadThatLive, new DefaultPathEdge(islesOfTheDeadThatLive.getRoute()));
        pathsGraph.addEdge(lorien, irerock, new DefaultPathEdge(irerock.getRoute()));
        pathsGraph.addEdge(lorien, ironHillDwarfHold, new DefaultPathEdge(ironHillDwarfHold.getRoute()));
        pathsGraph.addEdge(lorien, hennethAnnun, new DefaultPathEdge(hennethAnnun.getRoute()));
        pathsGraph.addEdge(greyHavens, himring, new DefaultPathEdge(himring.getRoute()));
        pathsGraph.addEdge(lorien, theLonelyMountain, new DefaultPathEdge(theLonelyMountain.getRoute()));
        pathsGraph.addEdge(edhellond, theStones, new DefaultPathEdge(theStones.getRoute()));
        pathsGraph.addEdge(edhellond, southronOasis, new DefaultPathEdge(southronOasis.getRoute()));
        pathsGraph.addEdge(edhellond, stoneCircle, new DefaultPathEdge(stoneCircle.getRoute()));
        pathsGraph.addEdge(lorien, shelobsLair, new DefaultPathEdge(shelobsLair.getRoute()));
        pathsGraph.addEdge(lorien, shrelKain, new DefaultPathEdge(shrelKain.getRoute()));
        pathsGraph.addEdge(rivendell, ruinedSignalTower, new DefaultPathEdge(ruinedSignalTower.getRoute()));
        pathsGraph.addEdge(lorien, sarnGoriwing, new DefaultPathEdge(sarnGoriwing.getRoute()));
        pathsGraph.addEdge(lorien, rhosgobel, new DefaultPathEdge(rhosgobel.getRoute()));
        pathsGraph.addEdge(edhellond, pelargir, new DefaultPathEdge(pelargir.getRoute()));
        pathsGraph.addEdge(rivendell, oldForest, new DefaultPathEdge(oldForest.getRoute()));
        pathsGraph.addEdge(rivendell, ostInEdhil, new DefaultPathEdge(ostInEdhil.getRoute()));
        pathsGraph.addEdge(rivendell, mountGram, new DefaultPathEdge(mountGram.getRoute()));
        pathsGraph.addEdge(lorien, mountDoom, new DefaultPathEdge(mountDoom.getRoute()));
        pathsGraph.addEdge(lorien, minasMorgul, new DefaultPathEdge(minasMorgul.getRoute()));
        pathsGraph.addEdge(rivendell, lossadanCamp, new DefaultPathEdge(lossadanCamp.getRoute()));
        pathsGraph.addEdge(edhellond, wosePassageHold, new DefaultPathEdge(wosePassageHold.getRoute()));
        pathsGraph.addEdge(rivendell, theWhiteTowers, new DefaultPathEdge(theWhiteTowers.getRoute()));
        pathsGraph.addEdge(lorien, woodmenTown, new DefaultPathEdge(woodmenTown.getRoute()));
        pathsGraph.addEdge(edhellond, variagCamp, new DefaultPathEdge(variagCamp.getRoute()));
        pathsGraph.addEdge(rivendell, weathertop, new DefaultPathEdge(weathertop.getRoute()));
        pathsGraph.addEdge(edhellond, tolfalas, new DefaultPathEdge(tolfalas.getRoute()));
        pathsGraph.addEdge(edhellond, valeOfErech, new DefaultPathEdge(valeOfErech.getRoute()));
        pathsGraph.addEdge(lorien, theWindThrone, new DefaultPathEdge(theWindThrone.getRoute()));

        return pathsGraph;
    }
}